<h1> Regresion Lineal Multiple </h1>

In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [132]:
df = pd.read_csv("./50_Startups.csv")

In [133]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [134]:
# tengo distintos estados, california, new york y florida, asi que hay que separarlos en variables dummies
# x = pd.DataFrame(x)
x = pd.concat((x,pd.get_dummies(x.iloc[:, 3])),1)
x = x.drop([x.columns[3]], axis=1)
x

    R&D Spend  Administration  Marketing Spend  California  Florida  New York
0   165349.20       136897.80        471784.10           0        0         1
1   162597.70       151377.59        443898.53           1        0         0
2   153441.51       101145.55        407934.54           0        1         0
3   144372.41       118671.85        383199.62           0        0         1
4   142107.34        91391.77        366168.42           0        1         0
5   131876.90        99814.71        362861.36           0        0         1
6   134615.46       147198.87        127716.82           1        0         0
7   130298.13       145530.06        323876.68           0        1         0
8   120542.52       148718.95        311613.29           0        0         1
9   123334.88       108679.17        304981.62           1        0         0
10  101913.08       110594.11        229160.95           0        1         0
11  100671.96        91790.61        249744.55           1        0         0
12   93863.75       127320.38        249839.44           0        1         0
13   91992.39       135495.07        252664.93           1        0         0
14  119943.24       156547.42        256512.92           0        1         0
15  114523.61       122616.84        261776.23           0        0         1
16   78013.11       121597.55        264346.06           1        0         0
17   94657.16       145077.58        282574.31           0        0         1
18   91749.16       114175.79        294919.57           0        1         0
19   86419.70       153514.11             0.00           0        0         1
20   76253.86       113867.30        298664.47           1        0         0
21   78389.47       153773.43        299737.29           0        0         1
22   73994.56       122782.75        303319.26           0        1         0
23   67532.53       105751.03        304768.73           0        1         0
24   77044.01        99281.34        140574.81           0        0         1
25   64664.71       139553.16        137962.62           1        0         0
26   75328.87       144135.98        134050.07           0        1         0
27   72107.60       127864.55        353183.81           0        0         1
28   66051.52       182645.56        118148.20           0        1         0
29   65605.48       153032.06        107138.38           0        0         1
30   61994.48       115641.28         91131.24           0        1         0
31   61136.38       152701.92         88218.23           0        0         1
32   63408.86       129219.61         46085.25           1        0         0
33   55493.95       103057.49        214634.81           0        1         0
34   46426.07       157693.92        210797.67           1        0         0
35   46014.02        85047.44        205517.64           0        0         1
36   28663.76       127056.21        201126.82           0        1         0
37   44069.95        51283.14        197029.42           1        0         0
38   20229.59        65947.93        185265.10           0        0         1
39   38558.51        82982.09        174999.30           1        0         0
40   28754.33       118546.05        172795.67           1        0         0
41   27892.92        84710.77        164470.71           0        1         0
42   23640.93        96189.63        148001.11           1        0         0
43   15505.73       127382.30         35534.17           0        0         1
44   22177.74       154806.14         28334.72           1        0         0
45    1000.23       124153.04          1903.93           0        0         1
46    1315.46       115816.21        297114.46           0        1         0
47       0.00       135426.92             0.00           1        0         0
48     542.05        51743.15             0.00           0        0         1
49       0.00       116983.80         45173.06           1        0         0

In [135]:
# pero aqui hay colinaridad, porque, si ya sabemos que una empresa no está en california ni en florida, entonces estará en new york,
# es decir, NY = 1-CA-FL, es decir, new york es una variable que depende de las 2 otras variables, así que la vamos a eliminar
# (podriamos haber eliminado cualquiera)
#?pd.DataFrame.drop
x = x.drop(columns=["New York"])
x

    R&D Spend  Administration  Marketing Spend  California  Florida
0   165349.20       136897.80        471784.10           0        0
1   162597.70       151377.59        443898.53           1        0
2   153441.51       101145.55        407934.54           0        1
3   144372.41       118671.85        383199.62           0        0
4   142107.34        91391.77        366168.42           0        1
5   131876.90        99814.71        362861.36           0        0
6   134615.46       147198.87        127716.82           1        0
7   130298.13       145530.06        323876.68           0        1
8   120542.52       148718.95        311613.29           0        0
9   123334.88       108679.17        304981.62           1        0
10  101913.08       110594.11        229160.95           0        1
11  100671.96        91790.61        249744.55           1        0
12   93863.75       127320.38        249839.44           0        1
13   91992.39       135495.07        252664.93           1        0
14  119943.24       156547.42        256512.92           0        1
15  114523.61       122616.84        261776.23           0        0
16   78013.11       121597.55        264346.06           1        0
17   94657.16       145077.58        282574.31           0        0
18   91749.16       114175.79        294919.57           0        1
19   86419.70       153514.11             0.00           0        0
20   76253.86       113867.30        298664.47           1        0
21   78389.47       153773.43        299737.29           0        0
22   73994.56       122782.75        303319.26           0        1
23   67532.53       105751.03        304768.73           0        1
24   77044.01        99281.34        140574.81           0        0
25   64664.71       139553.16        137962.62           1        0
26   75328.87       144135.98        134050.07           0        1
27   72107.60       127864.55        353183.81           0        0
28   66051.52       182645.56        118148.20           0        1
29   65605.48       153032.06        107138.38           0        0
30   61994.48       115641.28         91131.24           0        1
31   61136.38       152701.92         88218.23           0        0
32   63408.86       129219.61         46085.25           1        0
33   55493.95       103057.49        214634.81           0        1
34   46426.07       157693.92        210797.67           1        0
35   46014.02        85047.44        205517.64           0        0
36   28663.76       127056.21        201126.82           0        1
37   44069.95        51283.14        197029.42           1        0
38   20229.59        65947.93        185265.10           0        0
39   38558.51        82982.09        174999.30           1        0
40   28754.33       118546.05        172795.67           1        0
41   27892.92        84710.77        164470.71           0        1
42   23640.93        96189.63        148001.11           1        0
43   15505.73       127382.30         35534.17           0        0
44   22177.74       154806.14         28334.72           1        0
45    1000.23       124153.04          1903.93           0        0
46    1315.46       115816.21        297114.46           0        1
47       0.00       135426.92             0.00           1        0
48     542.05        51743.15             0.00           0        0
49       0.00       116983.80         45173.06           1        0

In [136]:
# separo entre train y test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

<h2> Regresion Lineal

In [137]:
from sklearn.linear_model import LinearRegression
regresion = LinearRegression()
regresion.fit(x_train, y_train)

LinearRegression()

In [138]:
# prediccion de los datos
y_pred = regresion.predict(x_test)

In [139]:
# parecen ser muy buenas predicciones :D
print((y_test.values-y_pred)/y_test)

28    0.002587
11    0.080945
10    0.093581
41    0.074843
2     0.065495
27   -0.106210
38    0.164687
31   -0.013419
22   -0.032779
4    -0.010429
Name: Profit, dtype: float64

## creacion del mejor modelo lineal multiple con el método de la eliminación hacia atrás

El modelo es del tipo
$$y = x_0 + x_1 *a_1 + x_2*a_2 + ... + x_n * a_n$$
y queremos saber cual de los coeficientes $x_n$ no es importante, es decir, cuando $a_n \approx 0$  
tambien queremos saber si $x_0 \approx 0$, asi que vamos a agregar una columna de 1's

In [140]:
import statsmodels.api as sm

In [141]:
# agrego la columna de 1's
x.insert(loc=0, column="a_0", value=np.ones(df.shape[0]))
#df["a_0"] = np.ones(df.shape[0])
x

    a_0  R&D Spend  Administration  Marketing Spend  California  Florida
0   1.0  165349.20       136897.80        471784.10           0        0
1   1.0  162597.70       151377.59        443898.53           1        0
2   1.0  153441.51       101145.55        407934.54           0        1
3   1.0  144372.41       118671.85        383199.62           0        0
4   1.0  142107.34        91391.77        366168.42           0        1
5   1.0  131876.90        99814.71        362861.36           0        0
6   1.0  134615.46       147198.87        127716.82           1        0
7   1.0  130298.13       145530.06        323876.68           0        1
8   1.0  120542.52       148718.95        311613.29           0        0
9   1.0  123334.88       108679.17        304981.62           1        0
10  1.0  101913.08       110594.11        229160.95           0        1
11  1.0  100671.96        91790.61        249744.55           1        0
12  1.0   93863.75       127320.38        249839.44           0        1
13  1.0   91992.39       135495.07        252664.93           1        0
14  1.0  119943.24       156547.42        256512.92           0        1
15  1.0  114523.61       122616.84        261776.23           0        0
16  1.0   78013.11       121597.55        264346.06           1        0
17  1.0   94657.16       145077.58        282574.31           0        0
18  1.0   91749.16       114175.79        294919.57           0        1
19  1.0   86419.70       153514.11             0.00           0        0
20  1.0   76253.86       113867.30        298664.47           1        0
21  1.0   78389.47       153773.43        299737.29           0        0
22  1.0   73994.56       122782.75        303319.26           0        1
23  1.0   67532.53       105751.03        304768.73           0        1
24  1.0   77044.01        99281.34        140574.81           0        0
25  1.0   64664.71       139553.16        137962.62           1        0
26  1.0   75328.87       144135.98        134050.07           0        1
27  1.0   72107.60       127864.55        353183.81           0        0
28  1.0   66051.52       182645.56        118148.20           0        1
29  1.0   65605.48       153032.06        107138.38           0        0
30  1.0   61994.48       115641.28         91131.24           0        1
31  1.0   61136.38       152701.92         88218.23           0        0
32  1.0   63408.86       129219.61         46085.25           1        0
33  1.0   55493.95       103057.49        214634.81           0        1
34  1.0   46426.07       157693.92        210797.67           1        0
35  1.0   46014.02        85047.44        205517.64           0        0
36  1.0   28663.76       127056.21        201126.82           0        1
37  1.0   44069.95        51283.14        197029.42           1        0
38  1.0   20229.59        65947.93        185265.10           0        0
39  1.0   38558.51        82982.09        174999.30           1        0
40  1.0   28754.33       118546.05        172795.67           1        0
41  1.0   27892.92        84710.77        164470.71           0        1
42  1.0   23640.93        96189.63        148001.11           1        0
43  1.0   15505.73       127382.30         35534.17           0        0
44  1.0   22177.74       154806.14         28334.72           1        0
45  1.0    1000.23       124153.04          1903.93           0        0
46  1.0    1315.46       115816.21        297114.46           0        1
47  1.0       0.00       135426.92             0.00           1        0
48  1.0     542.05        51743.15             0.00           0        0
49  1.0       0.00       116983.80         45173.06           1        0

In [142]:
# creo la variable donde estan todas las variables, luego se irán dejando solo las optimas
variablesOptimas = x
regresionLineal = sm.OLS(y, variablesOptimas).fit()
regresionLineal.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Thu, 02 Jun 2022   Prob (F-statistic):           1.34e-27
Time:                        23:34:44   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
a_0              5.008e+04   6952.587      7.204      0.000    3.61e+04    6.41e+04
R&D Spend           0.8060      0.046     17.369      0.000       0.712       0.900
Administration     -0.0270      0.052     -0.517      0.608      -0.132       0.078
Marketing Spend     0.0270      0.017      1.574      0.123      -0.008       0.062
California         41.8870   3256.039      0.013      0.990   -6520.229    6604.003
Florida           240.6758   3338.857      0.072      0.943   -6488.349    6969.701
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Hay que fijarse en el p_valor, mientras las bajo sea el p_valor, más importante es la variable, pues significa que no se sabe muy bien por donde irá la probabilidad de que algo ocurra, y por tanto, va a modificar más los datos  
El p_valor mide la probabilidad de que azarozamente un valor caiga en el 95% de los datos, mientras más facilmente caiga ahí, mayor será el p_valor
por tanto, si el p valor es bajo, entonces significa que esa variable ... ?

### Lo importante, eliminamos las que tienen p_valor más alto
(hasta que p_valor (P>|t|) sea menor a 0.05)

In [143]:
variablesOptimas = variablesOptimas.drop(["California"], axis=1)
regresionLineal = sm.OLS(y, variablesOptimas).fit()
regresionLineal.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Thu, 02 Jun 2022   Prob (F-statistic):           8.49e-29
Time:                        23:34:44   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
a_0              5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
R&D Spend           0.8060      0.046     17.606      0.000       0.714       0.898
Administration     -0.0270      0.052     -0.523      0.604      -0.131       0.077
Marketing Spend     0.0270      0.017      1.592      0.118      -0.007       0.061
Florida           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [144]:
variablesOptimas = variablesOptimas.drop(["Florida"], axis=1)
regresionLineal = sm.OLS(y, variablesOptimas).fit()
regresionLineal.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Thu, 02 Jun 2022   Prob (F-statistic):           4.53e-30
Time:                        23:34:44   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
a_0              5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
R&D Spend           0.8057      0.045     17.846      0.000       0.715       0.897
Administration     -0.0268      0.051     -0.526      0.602      -0.130       0.076
Marketing Spend     0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [145]:
variablesOptimas = variablesOptimas.drop(["Administration"], axis=1)
regresionLineal = sm.OLS(y, variablesOptimas).fit()
regresionLineal.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Thu, 02 Jun 2022   Prob (F-statistic):           2.16e-31
Time:                        23:34:44   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
a_0              4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
R&D Spend           0.7966      0.041     19.266      0.000       0.713       0.880
Marketing Spend     0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

aquí debería eliminar "marketing spend", porque si p_valor es superior a 0.05, pero es 0.06, asi que lo dejo, asi que quedamos con este modelo :), veamos cuan diferente es

In [146]:
x_train2, x_test2, y_train2, y_test2 = train_test_split(variablesOptimas, y, test_size=0.2, random_state=0)
regresion_ajustada = LinearRegression()
regresion_ajustada.fit(x_train2, y_train2)
y_pred2 = regresion_ajustada.predict(x_test2)
df = pd.DataFrame(y_pred, y_pred2)
df

                           0
102284.646052  103015.201598
133873.923838  132582.277608
134182.149517  132447.738452
73701.106936    71976.098513
180642.252997  178537.482211
114717.249039  116161.242302
68335.075753    67851.692097
97433.459223    98791.733747
114580.921365  113969.435330
170343.319795  167921.065696

Al final, 2 variables son las más importantes para predecir las ganancias de las compañias, gasto en i+d y gasto en publicidad